### ISSUE TITLE
[Feature] Guia de como usar nossa badge

### ISSUE THREAD

**Issue by ItaloSa** [ufrpe-devs/comunidade#47]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Criamos uma badge do UFRPE Devs, mas ainda não temos um guia de como ser utilizado pelas pessoas.

**Descreva a solução que você gostaria**
Podemos ter na página principal um tópico que indique a existência da badge e como usar. 

**Descreva as alternativas que você considerou**
Talvez um link no `README.md` para uma página só pra falar da badge.

**Contexto adicional**
Nossa badge:

[![UFRPE Devs badge](https://raw.githubusercontent.com/ufrpe-devs/comunidade/main/media/ufrpe-devs-badge.svg)](https://github.com/ufrpe-devs/comunidade)

Como usar:
```
[![UFRPE Devs badge](https://raw.githubusercontent.com/ufrpe-devs/comunidade/main/media/ufrpe-devs-badge.svg)](https://github.com/ufrpe-devs/comunidade)
```

**Comment by RafaelTomas** [comment]
Posso pegar essa?
